version: '3.8'

services:
  bot:
    build: .
    depends_on:
      - redis
      - postgres
    environment:
      - TZ=UTC
      # Log settings
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      - LOG_ADD_SOURCE=true
      # Bot settings
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_SYNC_COMMANDS=true
      - BOT_DEV_MODE=false
      - BOT_VERSION=1.0.0
      # Database settings
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_SSL_MODE=disable
      # Redis settings
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-friemon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-friemonpass}
      POSTGRES_DB: ${POSTGRES_DB:-friemon}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
