version: '3.9'

services:
  # The main application service for the Discord bot
  bot:
    build:
      context: .
      # Pass build arguments to embed git info into the binary
      args:
        COMMIT: ${COMMIT:-unknown}
        BRANCH: ${BRANCH:-unknown}
    container_name: friemon_bot
    restart: unless-stopped
    environment:
      # It's recommended to use environment variables to configure the bot,
      # as they override the values in config.toml
      - TZ=UTC
      # Log settings
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-text}
      # Bot settings
      - BOT_TOKEN=${BOT_TOKEN:?err_bot_token_not_set}
      - BOT_SYNC_COMMANDS=${BOT_SYNC_COMMANDS:-true}
      - BOT_DEV_MODE=${BOT_DEV_MODE:-false}
      # Database connection settings
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-friemon}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-friemonpass}
      - DB_NAME=${POSTGRES_DB:-friemon}
      - DB_SSL_MODE=disable
      # Redis connection settings
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
    networks:
      - friemon_net
    # depends_on with condition ensures the bot only starts after its
    # dependencies are healthy and ready to accept connections.
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Redis service for caching and transient data storage
  redis:
    image: redis:7.2-alpine
    container_name: friemon_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - friemon_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL service for persistent data storage
  postgres:
    image: postgres:16.3-alpine
    container_name: friemon_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-friemon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-friemonpass}
      POSTGRES_DB: ${POSTGRES_DB:-friemon}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - friemon_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-friemon} -d ${POSTGRES_DB:-friemon}"]
      interval: 10s
      timeout: 5s
      retries: 5

# Define the network for inter-service communication
networks:
  friemon_net:
    driver: bridge

# Define named volumes for persistent data
volumes:
  postgres_data:
  redis_data: